### ISSUE TITLE
some tables do not exist

### ISSUE THREAD

**Issue by AlaiY95** [cM2908/leetcode-sql#1]
Hi, 

I have loaded the dump file that was successful as I have 322 tables loaded into Postgres. 

However when I run query "175. Combine Two Tables.sql" from the easy folder, I get the error 
` ERROR:  relation "person_175" does not exist
LINE 1: SELECT * FROM person_175;
                      ^
SQL state: 42P01
Character: 15`

**Comment by cM2908** [comment]
@AlaiY95 Apart from running the query, did you check whether that table got created or not? 

Please check using information schema.

Please make sure you are querying the same database to which you've imported the dump

**Comment by AlaiY95** [comment]
@cM2908 can confirm that table was not created initially. It has tables person_182, person_196 but not person_175. Strange but I can live without doing the query. Just thought if there was an updated dump file

**Comment by cM2908** [comment]
@AlaiY95 I'll check and update.

Thanks though, appreciate it.

**Comment by cM2908** [comment]
@AlaiY95, Because this data has no records, I haven't created it. But the newer dump consists this table

Thanks
